language: node_js

sudo: false

cache: npm

script:
  - npm run lint
  - npm run test:coverage
  - npm link
  - mkdir -p ./__temp__
  - swagjs gen ./example -i ./example/base_swagger.yml -o ./__temp__/swagger.json --model-pattern .model. --tags ./example/tags.yml

after_script:
  - npm run coveralls

deploy:
  provider: npm
  skip_cleanup: true
  email: ${NPM_EMAIL}
  api_key: ${NPM_TOKEN}
  on:
    branch: master
    tags: true
