language: node_js

sudo: false

node_js:
  - '6'
  - 'node'

script:
  - npm run lint
  - npm run test:coverage
  - npm link
  - swagjs gen ./example -i ./example/base_swagger.yml --model-pattern .model.

after_script:
  - npm run coveralls
